# 실전/모의투자 환경 설정
is_mock: true

kiwoom:
  # ----------------------------------------------------------------
  # 실거래 API 관련
  app_key: "gSOByJK1n8ZldPnuaj-l_EL-bgYyGbTCf1lRlbnl3Gc"
  app_secret: "M3PcxH6_jD2EFJlLIUTG9sBitEJvi6cpYBrE2U1fc5c"
  account_no: "60002730"
  # ----------------------------------------------------------------

  # ----------------------------------------------------------------
  # 모의투자 API 관련
  mock_app_key: "06u6iYN8tZfcKy6kZS8gX5uZpSlhkVhjucA5Ag583mE"
  mock_app_secret: "8PVQbj0B3mO1xe1jUg75TIV1v02ddGI5CAr87RehCr8"
  mock_account_no: "81135402"
  # ----------------------------------------------------------------

engine:
  screening_interval_minutes: 5 # 스크리닝 주기 (분) -> strategy 섹션으로 이동 권장

strategy:
  orb_timeframe: 15         # ORB 계산 시간 (분)
  breakout_buffer: 0.15     # 돌파 버퍼 (%)
  investment_amount_per_stock: 100000  # <-- 수정됨: 종목당 투자 금액 (10만원)
  take_profit_pct: 2.5      # 익절 기준 (%)
  stop_loss_pct: -1.0       # 고정 손절 기준 (%)
  # stop_loss_vwap_pct: 0.5   # VWAP 기준 손절 (%) -> risk_manager.py 에 VWAP 로직 추가 후 주석 해제

  # --- 다중 종목 관리 설정 ---
  max_target_stocks: 5       # 스크리닝 후 최대 관심 종목 수
  max_concurrent_positions: 5 # 동시에 보유할 최대 종목 수

  # --- 스크리닝 관련 설정 ---
  screening_interval_minutes: 5       # 스크리닝 주기 (분)
  screening_surge_timeframe_minutes: 5  # <-- 수정됨: 거래량 급증 비교 시간 (분, 숫자)
  screening_min_volume_threshold: 10   # <-- 수정됨: 최소 거래량 기준 (만주 단위 숫자, 예: 10 -> 만주)
  screening_min_price: 1000           # 최소 가격 기준 (원)
  screening_min_surge_rate: 100.0     # 최소 급증률 기준 (%)

  # --- Tick 처리 간격 설정 ---
  tick_interval_seconds: 5 # 개별 종목 Tick 처리 주기 (초)

# --- 자금 관리 설정 (향후 추가 예정) ---
  # investment_ratio: 0.1 # 예: 자산의 10% 투자
  # max_position_size: 10 # 예: 최대 10주